image: docker:27

stages:
  - build1
  - build2
  - push

variables:
  DOCKER_TLS_CERTDIR: ""   # 必须关掉，不然 docker 会走 dind
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

before_script:
  - docker version
  - docker info

build:
  stage: build1
  script:
    - docker build -t python -f dockerfile1
  only:
    - branches
  stage:build2
  script:
    - docker build -t vue3 -f dockerfile2
push:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - branches
